//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InkismMISEntities : DbContext
    {
        public InkismMISEntities()
            : base("name=InkismMISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountAppPermission> AccountAppPermission { get; set; }
        public virtual DbSet<AccountWebPermission> AccountWebPermission { get; set; }
        public virtual DbSet<AppProgram> AppProgram { get; set; }
        public virtual DbSet<DvrInfo> DvrInfo { get; set; }
        public virtual DbSet<ErpItem> ErpItem { get; set; }
        public virtual DbSet<ESunBank> ESunBank { get; set; }
        public virtual DbSet<ExchangeRate> ExchangeRate { get; set; }
        public virtual DbSet<ExtendLog> ExtendLog { get; set; }
        public virtual DbSet<ExtendRole> ExtendRole { get; set; }
        public virtual DbSet<ExtendUser> ExtendUser { get; set; }
        public virtual DbSet<INVTC_BAK> INVTC_BAK { get; set; }
        public virtual DbSet<INVTC_DATA> INVTC_DATA { get; set; }
        public virtual DbSet<RetailInvoice> RetailInvoice { get; set; }
        public virtual DbSet<RetailSub> RetailSub { get; set; }
        public virtual DbSet<Sales_Report> Sales_Report { get; set; }
        public virtual DbSet<StoreBrand> StoreBrand { get; set; }
        public virtual DbSet<StoreCom> StoreCom { get; set; }
        public virtual DbSet<StoreData> StoreData { get; set; }
        public virtual DbSet<StoreDayRetail> StoreDayRetail { get; set; }
        public virtual DbSet<StoreDayRetailTarget> StoreDayRetailTarget { get; set; }
        public virtual DbSet<StoreManageArea> StoreManageArea { get; set; }
        public virtual DbSet<StoreManager> StoreManager { get; set; }
        public virtual DbSet<TAXI01_Bak> TAXI01_Bak { get; set; }
        public virtual DbSet<Retail> Retail { get; set; }
        public virtual DbSet<ExtendKeyWord> ExtendKeyWord { get; set; }
        public virtual DbSet<StoreMonthRetailKeyIn> StoreMonthRetailKeyIn { get; set; }
    }
}
