//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESunBank
    {
        public System.DateTime RecvDateTime { get; set; }
        public string RemoteIP { get; set; }
        public string Data { get; set; }
        public string ToOrderWebResult { get; set; }
        public string ToTestOrderWebResult { get; set; }
    }
}
