//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailInvoice
    {
        public string StoreNo { get; set; }
        public string OrderNo { get; set; }
        public int SerialNo { get; set; }
        public System.DateTime InvoiceDateTime { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal InvoiceMoney { get; set; }
        public byte IsCancel { get; set; }
        public decimal Cash { get; set; }
        public decimal CreditCard { get; set; }
        public string DataSource { get; set; }
        public decimal EasyCard { get; set; }
        public string UCode { get; set; }
        public bool FromAPI { get; set; }
        public decimal Tax { get; set; }
    }
}
