//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retail
    {
        public string StoreNo { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDateTime { get; set; }
        public decimal Cash { get; set; }
        public decimal CreditCard { get; set; }
        public decimal EasyCard { get; set; }
        public decimal LinePay { get; set; }
        public decimal Coupon { get; set; }
        public decimal Discount { get; set; }
        public decimal SubPrice { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal TotalPrice { get; set; }
        public int Adult { get; set; }
        public int Child { get; set; }
        public byte IsCancel { get; set; }
        public string DataSource { get; set; }
        public string CreateBy { get; set; }
        public string OrderType { get; set; }
        public Nullable<System.DateTime> RetailDate { get; set; }
        public Nullable<decimal> UberEats { get; set; }
        public Nullable<decimal> FoodPanda { get; set; }
        public Nullable<decimal> Deliveroo { get; set; }
        public Nullable<decimal> iPass { get; set; }
        public Nullable<decimal> iCash { get; set; }
        public Nullable<decimal> HappyCash { get; set; }
        public Nullable<bool> FromAPI { get; set; }
    }
}
