//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailSub
    {
        public string StoreNo { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDateTime { get; set; }
        public int SerialNo { get; set; }
        public string ProductName { get; set; }
        public int ProductCount { get; set; }
        public decimal Price { get; set; }
        public decimal SubPrice { get; set; }
        public decimal Discount { get; set; }
        public decimal TotalPrice { get; set; }
        public string DataSource { get; set; }
        public Nullable<byte> IsCancel { get; set; }
        public string Options { get; set; }
        public Nullable<System.DateTime> RetailDate { get; set; }
        public Nullable<bool> FromAPI { get; set; }
        public string ProductID { get; set; }
    }
}
