//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Report
    {
        public string xID { get; set; }
        public int Sales_Target_ID { get; set; }
        public string StoreNo { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> Sales_Predict { get; set; }
        public Nullable<int> Sales_Real { get; set; }
        public Nullable<int> Sales_Predict_Day { get; set; }
        public Nullable<int> Sales_Predict_Day_Record { get; set; }
        public Nullable<int> Sales_Predict_Night { get; set; }
        public Nullable<int> Sales_Predict_Night_Record { get; set; }
        public Nullable<double> Human_Predict { get; set; }
        public Nullable<double> Human_Real { get; set; }
        public Nullable<double> Human_Predict_Day { get; set; }
        public Nullable<double> Human_Predict_Day_Record { get; set; }
        public Nullable<double> Human_Predict_Night { get; set; }
        public Nullable<double> Human_Predict_Night_Record { get; set; }
        public Nullable<double> Sales_Predict_Total { get; set; }
        public Nullable<double> Sales_Real_Total { get; set; }
        public string StoreName { get; set; }
        public string City_Name { get; set; }
        public string Morning_Weather { get; set; }
        public string Evening_Weather { get; set; }
        public Nullable<int> Daily_Compare { get; set; }
        public Nullable<double> Daily_Percent { get; set; }
        public Nullable<double> CU_Percent { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Sales_Day_Count { get; set; }
        public Nullable<int> Sales_Night_Count { get; set; }
    }
}
