//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreData()
        {
            this.ExtendUser = new HashSet<ExtendUser>();
        }
    
        public string StoreNo { get; set; }
        public string StoreErpNo { get; set; }
        public string StoreErpTaxNo { get; set; }
        public string StoreErpCustID { get; set; }
        public string StoreBrand { get; set; }
        public string StoreCom { get; set; }
        public int StoreType { get; set; }
        public string StoreName { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<byte> Closed { get; set; }
        public string CurrencyID { get; set; }
        public string Address { get; set; }
        public string LatLng { get; set; }
        public string AreaName { get; set; }
        public string Manager1 { get; set; }
        public string Manager2 { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string StoreErpCom { get; set; }
        public string RetailDataAPIToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtendUser> ExtendUser { get; set; }
    }
}
