//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreDayRetail
    {
        public string StoreNo { get; set; }
        public System.DateTime RetailDate { get; set; }
        public decimal TotalRetail { get; set; }
        public int OrderCount { get; set; }
        public decimal DineIn { get; set; }
        public int DineInCount { get; set; }
        public decimal TakeOut { get; set; }
        public int TakeOutCount { get; set; }
        public decimal TakeSelf { get; set; }
        public int TakeSelfCount { get; set; }
        public decimal Delivery { get; set; }
        public int DeliveryCount { get; set; }
        public decimal DayRetail { get; set; }
        public int DayCount { get; set; }
        public decimal NightRetail { get; set; }
        public int NightCount { get; set; }
    }
}
