//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreDayRetailTarget
    {
        public string StoreNo { get; set; }
        public System.DateTime RetailDate { get; set; }
        public decimal DayRetailTarget { get; set; }
        public decimal NightRetailTarget { get; set; }
        public decimal DayManHourPredict { get; set; }
        public decimal NightManHourPredict { get; set; }
        public decimal DayManHour { get; set; }
        public decimal NightManHour { get; set; }
    }
}
