//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSite.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarketSite.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 420台中市豐原區向陽路376巷16號 的當地語系化字串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全部 的當地語系化字串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年營收(原幣) 的當地語系化字串。
        /// </summary>
        public static string AnnualRevenue {
            get {
                return ResourceManager.GetString("AnnualRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年營收(新台幣) 的當地語系化字串。
        /// </summary>
        public static string AnnualRevenueNTD {
            get {
                return ResourceManager.GetString("AnnualRevenueNTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回到列表 的當地語系化字串。
        /// </summary>
        public static string BackList {
            get {
                return ResourceManager.GetString("BackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取餐方式 的當地語系化字串。
        /// </summary>
        public static string CarryType {
            get {
                return ResourceManager.GetString("CarryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 變更密碼 的當地語系化字串。
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡我們 的當地語系化字串。
        /// </summary>
        public static string ContactUS {
            get {
                return ResourceManager.GetString("ContactUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 幣別 的當地語系化字串。
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 來客數與客單價 的當地語系化字串。
        /// </summary>
        public static string CustomePrice {
            get {
                return ResourceManager.GetString("CustomePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 每日業績報表 的當地語系化字串。
        /// </summary>
        public static string DailyReport {
            get {
                return ResourceManager.GetString("DailyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 逐日營收 的當地語系化字串。
        /// </summary>
        public static string DailyRevenue {
            get {
                return ResourceManager.GetString("DailyRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期 的當地語系化字串。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日班筆數 的當地語系化字串。
        /// </summary>
        public static string DayCount {
            get {
                return ResourceManager.GetString("DayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 墨力國際股份有限公司 的當地語系化字串。
        /// </summary>
        public static string Inkism {
            get {
                return ResourceManager.GetString("Inkism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 墨力官網 的當地語系化字串。
        /// </summary>
        public static string InkismSite {
            get {
                return ResourceManager.GetString("InkismSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        public static string Inquiry {
            get {
                return ResourceManager.GetString("Inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品項 的當地語系化字串。
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 大冷 的當地語系化字串。
        /// </summary>
        public static string LargeCold {
            get {
                return ResourceManager.GetString("LargeCold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 大熱 的當地語系化字串。
        /// </summary>
        public static string LargeHot {
            get {
                return ResourceManager.GetString("LargeHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入 的當地語系化字串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢日期區間最多6個月 的當地語系化字串。
        /// </summary>
        public static string MaxMonth {
            get {
                return ResourceManager.GetString("MaxMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中冷 的當地語系化字串。
        /// </summary>
        public static string MediumCold {
            get {
                return ResourceManager.GetString("MediumCold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中熱 的當地語系化字串。
        /// </summary>
        public static string MediumHot {
            get {
                return ResourceManager.GetString("MediumHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 甜一點 的當地語系化字串。
        /// </summary>
        public static string Microsugar {
            get {
                return ResourceManager.GetString("Microsugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金額 的當地語系化字串。
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 月 的當地語系化字串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 夜班筆數 的當地語系化字串。
        /// </summary>
        public static string NightCount {
            get {
                return ResourceManager.GetString("NightCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未分類 的當地語系化字串。
        /// </summary>
        public static string NoGroup {
            get {
                return ResourceManager.GetString("NoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總未稅金額 的當地語系化字串。
        /// </summary>
        public static string NonTaxTotal {
            get {
                return ResourceManager.GetString("NonTaxTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 正常糖 的當地語系化字串。
        /// </summary>
        public static string NormalSugar {
            get {
                return ResourceManager.GetString("NormalSugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單明細 的當地語系化字串。
        /// </summary>
        public static string OrderDetail {
            get {
                return ResourceManager.GetString("OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 打單人員 的當地語系化字串。
        /// </summary>
        public static string Orderer {
            get {
                return ResourceManager.GetString("Orderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單編號 的當地語系化字串。
        /// </summary>
        public static string OrderNum {
            get {
                return ResourceManager.GetString("OrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單金額 的當地語系化字串。
        /// </summary>
        public static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 打單時間 的當地語系化字串。
        /// </summary>
        public static string OrderTime {
            get {
                return ResourceManager.GetString("OrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數 的當地語系化字串。
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數量 的當地語系化字串。
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排行 的當地語系化字串。
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 各門店業績排行榜 的當地語系化字串。
        /// </summary>
        public static string RankingList {
            get {
                return ResourceManager.GetString("RankingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報表查詢 的當地語系化字串。
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營收 的當地語系化字串。
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 服務費 的當地語系化字串。
        /// </summary>
        public static string ServiceFee {
            get {
                return ResourceManager.GetString("ServiceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 平均客單價 的當地語系化字串。
        /// </summary>
        public static string SinglePrice {
            get {
                return ResourceManager.GetString("SinglePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 大小杯及糖量分析 的當地語系化字串。
        /// </summary>
        public static string SizeSuger {
            get {
                return ResourceManager.GetString("SizeSuger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 店號/店名 的當地語系化字串。
        /// </summary>
        public static string StoreNumName {
            get {
                return ResourceManager.GetString("StoreNumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 門市品項銷售排行 的當地語系化字串。
        /// </summary>
        public static string StoreProduct {
            get {
                return ResourceManager.GetString("StoreProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 門市歷年營收 的當地語系化字串。
        /// </summary>
        public static string StoreYear {
            get {
                return ResourceManager.GetString("StoreYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 小計 的當地語系化字串。
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2分之1糖 的當地語系化字串。
        /// </summary>
        public static string Sugar12 {
            get {
                return ResourceManager.GetString("Sugar12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3分之1糖 的當地語系化字串。
        /// </summary>
        public static string Sugar13 {
            get {
                return ResourceManager.GetString("Sugar13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 4分之1糖 的當地語系化字串。
        /// </summary>
        public static string Sugar14 {
            get {
                return ResourceManager.GetString("Sugar14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3分之2糖 的當地語系化字串。
        /// </summary>
        public static string Sugar23 {
            get {
                return ResourceManager.GetString("Sugar23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無糖 的當地語系化字串。
        /// </summary>
        public static string SugarFree {
            get {
                return ResourceManager.GetString("SugarFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到 的當地語系化字串。
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合計金額 的當地語系化字串。
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總筆數 的當地語系化字串。
        /// </summary>
        public static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總杯數 的當地語系化字串。
        /// </summary>
        public static string TotalCups {
            get {
                return ResourceManager.GetString("TotalCups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總交易金額 的當地語系化字串。
        /// </summary>
        public static string TotalRetail {
            get {
                return ResourceManager.GetString("TotalRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 來客數 的當地語系化字串。
        /// </summary>
        public static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年份 的當地語系化字串。
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
